docs: update

diff --git a/birch b/birch
--- a/birch
+++ b/birch
@@ -40,20 +40,23 @@ get_term_size() {
     shopt -s checkwinsize; (:;:)
 }
 
+setup_irc() {
+    exec 69>&-
+    exec 69<>"/dev/tcp/${host}/6667" || {
+        printf '%s\n' "error: Couldn't connect to $host." >&2
+        exit 1
+    }
+
+    printf 'NICK %s\n' "${nick:=$USER}" >&69
+    printf 'USER %s - - :%s\n' "$nick" "$nick" >&69
+    printf 'PASS %s\n' "$pass" >&69
+    printf 'JOIN %s\n' "$chan" >&69
+}
+
 redraw() {
     # Clear the screen and print the last N lines of history.
     printf '\e[2J\e[1;%sr' "$((LINES-1))"
     printf '%s' "${hist[@]: -$((LINES-1))}"
-}
-
-setup_irc() {
-    exec 69>&-
-    exec 69<>"/dev/tcp/${host}/6667" || exit 1
-
-    printf 'NICK %s\n' "$nick" >&69
-    printf 'USER %s - - :%s\n' "$nick" "$nick" >&69
-    printf 'PASS %s\n' "$pass" >&69
-    printf 'JOIN %s\n' "$chan" >&69
 }
 
 print_msg() {
@@ -181,7 +184,7 @@ get_args() {
         esac
     done
 
-    [[ -z $host || -z $nick ]] &&
+    [[ -z $host ]] &&
         usage
 }
 
@@ -197,6 +200,9 @@ usage() {
 
 main() {
     get_args "$@"
+    get_term_size
+    setup_irc
+    setup_terminal
 
     # Leave the terminal in a useable state and close the connection on exit.
     trap 'reset_terminal; exec 69>&-' EXIT
@@ -205,10 +211,6 @@ main() {
     # Instead of doing anything we set a variable and handle the
     # resize synchronously after the server and input read time-out.
     trap 'resize=1' WINCH
-
-    get_term_size
-    setup_terminal
-    setup_irc
 
     for ((;;)); {
         irc_send
